name: Build

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "*.md"
      - "*.sh"
      - "release.yaml"

  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    env:
      output: "${{ github.workspace }}/build/app/outputs/apk/release"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download AList Source Code
        run: |
          cd $GITHUB_WORKSPACE/alist-lib/scripts
          chmod +x *.sh
          ./init_alist.sh
          ./init_web.sh

      - uses: actions/setup-go@v4
        with:
          go-version: 1.22
          cache-dependency-path: ${{ github.workspace }}/alist-lib/alist/go.sum

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Build AList
        run: |
          cd $GITHUB_WORKSPACE/alist-lib/scripts
          chmod +x *.sh
          ./init_gomobile.sh
          ./gobind.sh
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: "AList"
          path: "${{ github.workspace }}/android/app/libs/*.aar"

      - name: Init Signature
        run: |
          # 1. 进入 android 目录
          cd android
          
          # 2. 写入 local.properties (移除引号干扰)
          echo "ALIAS_NAME=${{ secrets.ALIAS_NAME }}" > local.properties
          echo "ALIAS_PASSWORD=${{ secrets.ALIAS_PASSWORD }}" >> local.properties
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> local.properties
          # 这里设为 key.jks，因为 Gradle 会在 app 模块内寻找
          echo "KEY_PATH=key.jks" >> local.properties
          
          # 3. 将证书文件解码并直接放入 android/app 目录下
          mkdir -p app
          echo "${{ secrets.KEY_STORE }}" | base64 --decode > app/key.jks
          
          # 4. 调试输出：确认文件存在且有大小
          echo "Checking keystore file..."
          ls -l app/key.jks

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          cache: true

      - name: Build APK
        run: flutter build apk --split-per-abi --release

      - name: Init APP Version Name
        if: success()
        run: |
          # 动态提取版本号用于 Artifact 命名
          echo "ver_name=$(grep -m 1 'versionName' ${{ env.output }}/output-metadata.json | cut -d\" -f4)" >> $GITHUB_ENV

      - name: Upload App To Artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: "AListFlutter-v${{ env.ver_name }}"
          path: "${{ env.output }}/*.apk"
